### ISSUE TITLE
Syntax error in node-github-trend

### ISSUE THREAD

**Issue by rhysd** [rhysd/Trendy#4]
In main process, below syntax error occurred.

```
Uncaught Exception:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/home/hayashida/Dev/github.com/rhysd/Trendy/node_modules/github-trend/build/main.js:148:30)
    at Request.self.callback (/home/hayashida/Dev/github.com/rhysd/Trendy/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/hayashida/Dev/github.com/rhysd/Trendy/node_modules/request/request.js:1063:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/hayashida/Dev/github.com/rhysd/Trendy/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

The line `main.js:148:30` is below.

``` javascript
    Client.prototype.fetchGetAPI = function (repo) {
        var _this = this;
        return new Promise(function (resolve, reject) {
            var headers = {
                "User-Agent": "request",
                "Accept": "application/vnd.github.v3+json"
            };
            if (_this.token) {
                headers['Authorization'] = 'token ' + _this.token;
            }
            var opts = {
                url: "https://api.github.com/repos/" + repo.owner + "/" + repo.name,
                headers: headers
            };
            if (_this.scraper.config.proxy) {
                opts.proxy = _this.scraper.config.proxy;
            }
            request(opts, function (err, res, body) {
                if (err) {
                    reject(err);
                    return;
                }
                if (res.statusCode !== 200) {
                    reject(new Error("Invalid status: " + res.statusCode));
                    return;
                }
                resolve(JSON.parse(body));  // <- Here is main:148:30
            });
        });
    };
```

**Comment by rhysd** [comment]
It seems that this is a bug of Node.js because it occurred in `JSON.parse()`.

**Comment by rhysd** [comment]
I misunderstood.  The `SyntaxError` is for JSON.  So the body seems to be illegal as JSON.

**Comment by rhysd** [comment]
GitHub API sometimes returns invalid JSON as below

```
{ ... "url":"h:"https://api.github.com/repos/altercation/solarized/hooks", .. }
```

I caught the error and simply ignored it in node-github-trend 0.0.6.
